### ISSUE TITLE
Cluster icon position is very inaccurate

### ISSUE THREAD

**Issue by hipertracker** [istarkov/google-map-clustering-example#11]
The cluster icon is not placed on the map in the proper place. It's very inaccurate. :(

**Comment by hipertracker** [comment]
I created an example to reproduce the bug. https://github.com/hipertracker/cerebral-googlemap

**Comment by istarkov** [comment]
See problems in your code I'm pretty sure that all is very accurate. Or try to explain your issue more precisely.

**Comment by hipertracker** [comment]
The source code example is fixed (it had missing .env file). I don't know what I am doing wrong, `lat` and `lng` attributes of my cluster component does not correspond to the location of the cluster marker.  When I zoom out the map, the cluster icon is moving to the right place, more and more. I have created  a screencast showing the case: https://www.youtube.com/watch?v=EU9wSxTNOEA

**Comment by istarkov** [comment]
And now you want me to check your code? I have no time for this.
You can create a PR here with initial markers location as like as in your example, and if current example will work the same I'll take a look when i'll have time.

**Comment by hipertracker** [comment]
I found the what was the problem. It's was my cluster icon used as the background-image. It needed some margin left and top correction.
