### ISSUE TITLE
Passing props to <GMap > component

### ISSUE THREAD

**Issue by aylabyuk** [istarkov/google-map-clustering-example#9]
I understand you can change markers using

```
withState(
    'markers',
    'setMarkers',
    markersData
  ),
```
but is it also possible to use the usual way of passing props to set the markers?
`<Gmap markers={markers} /> `

**Comment by istarkov** [comment]
I don't understand your question.

**Comment by kunokdev** [comment]
He asks if it's possible to pass data to the component by adding prop 'markers' to the component in render method where he initialized it.

For example


```

class App extends React.Component {
  constructor(props){
    super(props)
    this.state = { markers: [] }
  }

  render(){
    return (<div>
      <Gmap markers={this.state.markers} />
      </div>
    )
  }
```
}
